var quotes = [
"Travel",
"Friends of Upcoming Birthday",
"Photography",
"Education",
"NPR",
"WiFi Connection",
"The New York Times",
"Food",
"Smartphone Owners",
"Primary Browser: Chrome",
"Jogging",
"Stanford University",
"Gmail Users",
"Away From Family",
"US Politics (Very Liberal)",
"Relationship status: married",
"Generation X",
"Family-based Households",
"All iOS devices",
"Storyteller",
"Millennials",
"Sports",
"Association football (Soccer)",
"Cosmetics",
"Music",
"Away From Hometown",
"Kickstarter",
"Yoga",
"uber",
"Facebook Page Admins",
"Frequent Travelers",
"Technology late adopters",
"English & Creative Writing",
"Friends of Recently Moved",
"The Daily Show",
"Hillary Clinton",
"Netflix",
"All Android devices",
"Friends of Newlywed",
"Shopping and fashion",
"Mobile phones",
"Fitness and wellness",
"Beer",
"Housemate-based Households",
"Technology",
"Video games",
"Televisions",
"Donald Trump",
"Coffee",
"The Huffington Post",
"Bernie Sanders",
"Primary Browser: Safari",
"Parenting",
"Parents (All)",
"Democratic Party (United States)",
"Technology early adopters",
"Restaurants",
"Shopping",
"Partido Republicano (Estados Unidos)",
"Tablet Owners",
"The New Yorker",
"Rock music",
"Event planning",
"TechCrunch",
"Marketing",
"Comedy movies",
"Clothing",
"Friends of Newly Engaged",
"League of Legends",
"Vice (magazine)",
"Coupons",
"Design",
"Rick and Morty","Samsung",
"Microsoft Outlook",
"Amazon.com",
"Frequent International Travelers",
"Nutrition",
"Love",
"US Politics (Liberal)",
"Wired (Magazine)",
"Real Estate",
"Online Advertising",
"College Football",
"American Football",
"Casual Gamer",
"Computers",
"Interested in Women",
"Expats (All)",
"TV",
"Duolingo",
"Gluten Free Diet","Commuters",
"Role Playing games",
"Bible",
"Facebook for iPhone",
"Software engineering",
"Tattoos",
"Spotify",
"Pokemon",
"University",
"shazam",
"The Onion",
"Musical film",
"Gilmore Girls",
"Child",
"Copenhagen Business School",
"Humans of New York",
"Reading",
"Luxury Goods",
"Game of Thrones",
"Veganism",
"Wine",
"Major League Baseball",
"US Politics (Moderate)",
"PC Gamer",
"Romantic Comedies",
"Architecture",
"Finance",
"Theatre",
"Instagram",
"Dental Floss",
"Science",
"Yahoo Email Addresses",
"Electronic Music",
"Pinterest",
"World of Warcraft",
"Time",
"The Washington Post",
"Computer and Mathematics",
"Independent Films",
"Dogs",
"Gardening",
"Returned from trip 1 week ago",
"Baby Boomers (US)",
"Game Consoles",
"Hair Products",
"Small Business Owner",
"Parent",
"Cats",
"Politics",
"Baseball",
"Mountains",
"Minecraft",
"Hiking",
"Fragrances",
"Toronto",
"Back to School (Marketing)",
"Personal Training",
"Do It Yourself (DIY)",
"Elon Musk",
"Nature",
"In-N-Out Burger",
"Music Festivals",
"Hotmail E-Mail Addresses",
"First Person Shooter Games",
"CrossFit",
"Daft Punk Discography",
"Golf",
"Baking",
"Air Travel",
"American Horror Story",
"Melania Trump",
"Astronomy",
"Astrology",
"Wearable Technology",
"Student",
"Friendship",
"(13-18 Years) Parents with Teenagers",
"Ethnic affinity: African American (US)",
"Ethnic affinity: Hispanic (US)",
"Fast Food",
"Meditation",
"Concerts",
"Consumer Electronics",
"US Politics (Conservative)",
"Hunting",
"Jewelry",
"Spas",
"Tea",
"ASOS.com",
"Sustainability",
"Philosophy",
"British Rock",
"Walmart",
"Tourism",
"Granola",
"The Wire",
"Planned Parenthood",
"Skiing",
"Dave Matthews Band",
"Physics",
"US Politics (Very Conservative)",
"Healthy Diet",
"Global Warming",
"LGBT Community",
"Breaking Bad",
"Canada",
"Artificial Intelligence",
"Google",
"Dance",
"Charity",
"Friends of Expats",
"Russia",
"Gambling",
"Cricket Enthusiasts",
"European Union",
"Heavy Metal Music",
"Robotics",
"Comics",
"Saturday Night Live",
"Outdoor Recreation",
"The Beatles Discograph",
"Martial Arts",
"Xbox",
"Trousers",
"Family of Expats",
"PlayStation 4",
"Agriculture",
"Tumblr",
"Sleep",
"Used Travel App",
"Whole Foods Market",
"Adventure Travel",
"Stephen King","Government Employees",
"Ambient Music",
"Paralympic Games",
"Calories",
"Small Business Owner",
"Edward Snowden",
"Harry Potter",
"Long Distance Relationship",
"Fitbit",
"The West Wing",
"Lifehacks",
"Swimming",
"Planned Parenthood",
"Smart TV",
"The Princess Bride",
"Buddhism",
"Marvel Comics",
"Bus",
"Birthday in 06 June",
"Southern United States",
"Kanye West",
"Puzzle Video Games",
"Military",
"Veteran",
"Psychedelic Rock",
"Cartoonist",
"(03-05 Years) Parents with Preschoolers",
"Call of Duty",
"Computer Programming",
"Childish Gambino",
"HBO",
"(0-12 months) New Parents", 
"Anime Movies",
"Streaming Media",
"Confederate States of America",
"Gyms",
"Triathlons",
"Self Care",
"American Culture",
"Groupon",
"Starbucks",
"Extraterrestrial Life",
"Musical Theatre",
"Newlywed (1 year)",
"YouTube",
"Vegetarianism",
"Europe",
"Labour Party (UK)",
"Jazz Music",
"Professional Wrestling",
"Minimalism",
"Justin Bieber",
"Police",
"The Walt Disney Company",
"McDonald's",
"Amsterdam",
"George Orwell",
"iPhone 5",
"Religion",
"The Big Bang Theory",
"Frank Ocean",
"Likely To Engage in Politics (Liberal)",
"Investigative Journalism",
"NASA",
"Home Based Business",
"Mattress",
"SpiderMan",
"Breathing",
"Apple Email Address",
"Sundance Film Festival",
"Christian Science",
"Sheep",
"Handbags",
"Reality TV Shows",
"Photo Uploaders",
"Skittles",
"Language Learning",
"Grandparent",
"Carbonated Water",
"(01-02 Years) Parents with Toddlers", 
"NASCAR",
"Perspiration",
"Human Sexuality",
"Leonard Cohen",
"Food Preparation and Services",
"Country Music",
"Chocolate",
"WikiLeaks",
"Puberty",
"Snack Food",
"Motorcycles",
"Left Wing Politics",
"Birthday on 12 December",
"New Job",
"1990s",
"GoPro",
"Energy Drinks",
"Bodybuilding",
"Amazon River",
"Birthday in 02 February",
"Socialism",
"American Jewish Culture",
"IKEA",
"Social Equality",
"Industrial Design",
"Birthday on 09 September",
"Bruce Springsteen",
"Sanitary Napkins",
"Birthday on 04 April",
"Artist",

]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}